#
# https://qiita.com/kawakawaryuryu/items/b0291c1bc1141a535263#set-up-docker-buildx より
#
# セットするシークレット
# DOCKERHUB_USERNAME: DockerHub ユーザ名
# DOCKERHUB_PASSWORD: DockerHub パスワード
# DOCKER_IMAGENAME: Dockerイメージ名
#

name: Build and Publish Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

  schedule:
    - cron: "0 0 1 * *"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "{name}=branch::${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Set BranchName
        run: echo "BRANCH_NAME=${{ steps.extract_branch.outputs.branch }}" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push(latest)
        if: contains(github.ref, 'main') || contains(github.ref, 'master')
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:latest

      - name: Build and push(release-${{ env.BRANCH_NAME }})
        if: (!(contains(github.ref, 'main') || contains(github.ref, 'master')))
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}:release-${{ env.BRANCH_NAME }}
